project_name: "hontodana"
language: typescript
ignored_dirs:
  - node_modules
  - .next
  - .kiro
max_file_size: 1048576
show_logs: true
use_lsp: true
security:
  exclude_sensitive:
    - .env
    - .env.local
    - .env.development.local
    - .env.test.local
  sanitize_logs: true
read_only: false
excluded_tools: []
initial_prompt:
